### ISSUE TITLE
Floating-point exception occurred even though the dt is smaller than suggestion

### ISSUE THREAD

**Issue by ZiXuanWan1994** [geodynamics/specfem3d#1339]
Dear all，
This exception occurred in the course of runinng slovers:

------------------------------------------
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7F8AC2534E08
#0  0x7F85AE9CCE08
#1  0x7F8AC2533F90
#2  0x7F8AC1C5E4AF
#1  0x7F85AE9CBF90
#2  0x7F85AE0F64AF
#0  0x7F7BE6C78E08
#1  0x7F7BE6C77F90
#2  0x7F7BE63A24AF
#3  0x404A2D in check_stability_ at check_stability.f90:91 (discriminator 13)
#3  0x404A2D in check_stability_ at check_stability.f90:91 (discriminator 13)
#3  0x404A2D in check_stability_ at check_stability.f90:91 (discriminator 13)
#4  0x470056 in iterate_time_ at iterate_time.F90:176
#4  0x470056 in iterate_time_ at iterate_time.F90:176
#4  0x470056 in iterate_time_ at iterate_time.F90:176
#5  0x4ED0CD in specfem3d_ at specfem3D.f90:376
#6  0x402DAF in xspecfem3d at program_specfem3D.f90:34
#7  0x7F85AE0E182F
#5  0x4ED0CD in specfem3d_ at specfem3D.f90:376
#6  0x402DAF in xspecfem3d at program_specfem3D.f90:34
#7  0x7F8AC1C4982F
#5  0x4ED0CD in specfem3d_ at specfem3D.f90:376
#6  0x402DAF in xspecfem3d at program_specfem3D.f90:34
#7  0x7F7BE638D82F
mpirun noticed that process rank 7 with PID 0 on node seis exited on signal 8 (Floating point exception).

--------------------------------------------------------------------------
The dt I set in par_file is strictly smaller than the output_solver suggests and the  max stability for wave velocities is 0.252825278 ，which should satisfy the CFL stability condition.
I don't know what caused this error and I could really use your help！

Best wishes!

wzx

**Comment by brioglade** [comment]
Hi zixuan,
Do you have any contact information?
Do you know how to transform cubit mesh file to specfem3d format?
Tang

**Comment by zhaojingxuan1028** [comment]
Hello, I have encountered a similar problem. Have you solved it

?

**Comment by jpampuero** [comment]
If you keep decreasing the time step, do you eventually get a stable simulation?
Does your mesh contain very deformed elements? For instance, elements with sharp corners, small angles; or very flat elements, with large aspect ratio. The time step suggested by the code can be overestimated in such cases.

**Comment by zhaojingxuan1028** [comment]
Thank you very much. My problem has been solved

**Comment by jpampuero** [comment]
Great. If you can explain here how you solved it, that could help other users who encounter similar problems.

**Comment by ablkvo** [comment]
Hi all, I have the same problem in inversion. everything is working in forward simulation but it is not working for all adjoint sources and I got this error:

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Any idea?
Best regards

**Comment by giuliasgattoni** [comment]
Hi all,
I'm having the same issue, although my mesh is regular and I'm setting a time step much smaller than the maximum suggested. The maximum dt suggested for my model is 0.08 and I get the error when setting it to 0.01.
If I decrease the time step then the solver runs fine, but I wonder why I cannot run it with a higher time step.
Can anyone help me understand what might be causing this problem?
Thank you very much in advance
Regards

**Comment by jpampuero** [comment]
Does your mesh contain very deformed elements? For instance, elements with sharp corners, small angles; or very flat elements, with large aspect ratio. The time step suggested by the code can be overestimated in such cases.

**Comment by giuliasgattoni** [comment]
No, the mesh is regular...
![Screenshot 2021-05-05 at 14 43 20](https://user-images.githubusercontent.com/83707017/117142833-72fd8a00-adb0-11eb-934a-813d2b00e42e.png)

**Comment by jpampuero** [comment]
What sort of absorbing boundaries are you using?
What values of Poisson's ratio?
What value of NGLL?

**Comment by giuliasgattoni** [comment]
I'm new to specfem honestly, and I'm setting up a model starting from some inherited files set up by a colleague. 
I'm using the 1D prem velocity model.
Absorbing boundaries: the STACEY_ABSORBING_CONDITIONS is set to true and all the rest to false.
NGLL is 2 (if I found the correct number).

Thanks a lot for your help.
